### ISSUE TITLE
Documentation error?

### ISSUE THREAD

**Issue by jlnd** [blinkreaction/drude-d7-testing#3]
Hello, I tried following the instructions in READMME.md, but ran into some issues. When I got to `dsh drush si -y` I got an error message `dsh: Unable to connect to the docker daemon`. So I tried `dsh up` but got an error: `Can't find a suitable configuration file in this directory or any parent. Are you in the right directory? Supported filenames: docker-compose.yml, docker-compose.yaml` so I tried `cp docker-compose.yml.dist docker-compose.yml` followed by `dsh up` again. Which worked, but then when I tried `dsh drush si -y` I got an error: `Command site-install needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command. The drush command 'si' could not be executed.`

So then, I started over. Instead of `dsh drush si -y`, I ran `dsh init` and that did the trick.

**Comment by lmakarov** [comment]
Hi @jlnd, thanks for pointing this out.
Looks like the manual steps are a bit outdated.

**Comment by amklose** [comment]
I think I'm also having this same issue. I ran `dsh drush si -y` from within ~/Projects/drude-testing/docroot/sites/default and I got `dsh: Unable to connect to the docker daemon`

I then tried `dsh init` and got the following:
```
Copying docker-compose.yml...
docroot/sites/default/settings.local.php already in place
Copying docroot/sites/site1/settings.local.php...
Copying docroot/sites/site2/settings.local.php...
dsh: Unable to connect to the docker daemon
```

Any advice?

**Comment by lmakarov** [comment]
@amklose Looks like the VM is not running and the project init script is not accounting for that (a bug).
Try `dsh up`, then `dsh int`

**Comment by lmakarov** [comment]
Should should be now resolved in both develop and master branches.
